name: Form.io JavaScript Forms and SDK
description: The core JavaScript Library for Form.io
author: The Form.io Developers
markdown: kramdown
highlighter: rouge
baseurl:
exclude: [package.json, gulpfile.js, node_modules, src, test, gulp]

